version: "3.7"

services:
  web:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    volumes:
      - .:/app
    command: /bin/run.sh
    ports:
      - 3000:3000
    depends_on:
      - postgresql
    env_file:
      - .env
    stdin_open: true
    tty: true
  redis:
    image: redis
  postgresql:
    platform: linux/x86_64
    image: postgres:13
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: notsecure
    ports:
      - 5432:5432

volumes:
  pg-data:
